source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.8'
# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.3.13', '< 0.5'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0', '>= 5.0.6'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby
gem 'coffee-rails', '>= 4.2.1'
# Use jquery as the JavaScript library
gem 'jquery-rails', '>= 4.3.1'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.6', '>= 2.6.3'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 1.0.0', group: :doc
#jquery ui
gem 'jquery-ui-rails', '>= 6.0.1'
#authentication and roles
gem 'devise', '>= 4.2.1'
gem 'cancancan'
gem 'rolify'
#bootstrap
gem 'bootstrap-sass'
# pagination
gem 'will_paginate'
gem 'will_paginate-bootstrap'
#validations
gem "jquery-validation-rails"
# scanning stuff
gem 'owasp-pipeline', '>= 0.8.7'
gem 'whenever'
gem 'chronic'
#github api
gem 'octokit'
#gitlab
gem 'gitlab', '>= 4.0.0'
#oauth
gem 'omniauth'
gem 'omniauth-github'
# redis && caching
gem 'redis-rails', '>= 5.0.1'
gem 'rails-settings-cached', '>= 0.6.5'
gem 'redis-namespace'
#sidekiq
gem 'sidekiq'
gem 'sidekiq-status'
gem 'sinatra', :require => false # for the UI
# ENV Variables
gem 'figaro'
#eager load notification
gem 'bullet', '>= 5.5.1'
#file upload
gem "paperclip", "~> 5.0.0"
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'
# Use Unicorn as the app server
# gem 'unicorn'
#file upload
gem 'remotipart', '~> 1.2'
#datatables
gem 'jquery-datatables-rails', github: 'rweng/jquery-datatables-rails'
# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development
# faker
gem 'faker'
#font awesome
gem "font-awesome-rails", ">= 4.7.0.1"
#nested from
gem "nested_form"
#jira integration
gem 'jira-ruby', github:'sumoheavy/jira-ruby'
gem 'soap4r-ng','2.0.3'
gem 'jira4r'
gem 'momentjs-rails', '>= 2.17.1'
gem 'bootstrap3-datetimepicker-rails', '~> 4.17.47'
gem 'puma'
gem 'foreman'
gem 'actionpack-action_caching', '>= 1.2.0'
gem 'spinjs-rails', '>= 1.4'
gem 'activerecord-session_store', '>= 1.0.0'
gem 'crack'
gem 'execjs'
gem 'therubyracer'
gem 'ruby-nmap'
#wp scan
gem 'typhoeus'
gem 'addressable'
gem 'ruby-progressbar'
gem 'terminal-table'
gem 'yajl-ruby'
#string formation
gem 'kramdown'
gem 'rails_autolink', '>= 1.1.6'
gem 'RedCloth'
gem 'loofah'
gem 'premailer-rails', '>= 1.9.5'
gem 'arachni'
gem 'arachni-reactor'
gem 'sidekiq-scheduler'
gem 'toastr-rails', '>= 1.0.3'
gem 'local_time', '>= 1.0.3'
gem 'sidekiq-statistic'
gem 'sidekiq-middleware'
gem 'sidekiq-retries'
gem 'god'
#gem 'tagsinput-rails'
gem 'tag-it-rails', '>= 2.0.0'
gem 'best_in_place', '>= 3.1.0'
gem 'spring', '>= 2.0.1'
gem 'pry-rails'
gem 'pry-byebug'
group :development, :test do
	# Call 'byebug' anywhere in the code to stop execution and get a debugger console
	gem 'byebug'
	gem 'rspec'
	gem "rspec-rails", ">= 3.5.2"
	gem "factory_girl_rails", ">= 4.8.0"
	gem 'capybara'
	gem 'spring-commands-rspec', '>= 1.0.4'
	gem 'database_cleaner'

end

group :development do
	# Access an IRB console on exception pages or by using <%= console %> in views
	gem 'web-console', '~> 2.3', '>= 2.3.0'
	gem 'better_errors'
	gem 'binding_of_caller'
	# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
	#gem 'spring'
end
group :test do
	gem 'webmock', '>=1.17.2'
	gem 'simplecov', '>= 0.14.1'
end
