source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '6.1.7.3'
# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.3.13', '< 0.5'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 6.0', '>= 6.0.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby
gem 'coffee-rails', '>= 4.2.2'
# Use jquery as the JavaScript library
gem 'jquery-rails', '>= 4.4.0'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.6', '>= 2.6.4'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 1.0.0', group: :doc
#jquery ui
gem 'jquery-ui-rails'
#authentication and roles
gem 'devise', '>= 4.7.1'
gem 'cancancan'
gem 'rolify'
#bootstrap
gem 'bootstrap-sass', '>= 3.4.0'
# pagination
gem 'will_paginate'
gem 'will_paginate-bootstrap'
#validations
gem "jquery-validation-rails"
# scanning stuff
gem 'owasp-pipeline', '>= 0.8.7'
gem 'whenever'
gem 'chronic'
#github api
gem 'octokit'
#gitlab
gem 'gitlab', '>= 4.0.0'
#oauth
gem 'omniauth', '>= 2.1.0'
gem 'omniauth-github', '>= 2.0.0'
# redis && caching
gem 'redis-rails', '>= 5.0.2'
gem 'rails-settings-cached'
gem 'redis-namespace'
#sidekiq
gem 'sidekiq', '>= 6.2.1'
gem 'sidekiq-status'
gem 'sinatra', '>= 2.2.3', :require => false # for the UI
# ENV Variables
gem 'figaro'
#eager load notification
gem 'bullet'
#file upload
gem "paperclip", "~> 5.2.1"
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'
# Use Unicorn as the app server
# gem 'unicorn'
#file upload
gem 'remotipart', '~> 1.2'
#datatables
gem 'jquery-datatables-rails', github: 'rweng/jquery-datatables-rails'
# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development
# faker
gem 'faker'
#font awesome
gem "font-awesome-rails", ">= 4.7.0.6"
#nested from
gem "nested_form"
#jira integration
gem 'jira-ruby', github:'sumoheavy/jira-ruby'
gem 'soap4r-ng','2.0.3'
gem 'jira4r'
gem 'momentjs-rails', '>= 2.17.1'
gem 'bootstrap3-datetimepicker-rails', '~> 4.17.47'
gem 'puma', '>= 4.3.12'
gem 'foreman'
gem 'actionpack-action_caching', '>= 1.2.1'
gem 'spinjs-rails'
gem 'activerecord-session_store', '>= 2.0.0'
gem 'crack'
gem 'execjs'
gem 'therubyracer'
gem 'ruby-nmap'
#wp scan
gem 'typhoeus'
gem 'addressable', '>= 2.8.0'
gem 'ruby-progressbar'
gem 'terminal-table'
gem 'yajl-ruby', '>= 1.4.2'
#string formation
gem 'kramdown', '>= 2.3.0'
gem 'rails_autolink'
gem 'RedCloth'
gem 'loofah', '>= 2.19.1'
gem 'premailer-rails', '>= 1.10.3'
gem 'arachni', '>= 1.6.1.3'
gem 'arachni-reactor'
gem 'sidekiq-scheduler'
gem 'toastr-rails'
gem 'local_time'
gem 'sidekiq-statistic', '>= 1.4.0'
gem 'sidekiq-middleware'
gem 'sidekiq-retries'
gem 'god'
#gem 'tagsinput-rails'
gem 'tag-it-rails'
gem 'best_in_place'
gem 'spring'
gem 'pry-rails'
gem 'pry-byebug'
group :development, :test do
	# Call 'byebug' anywhere in the code to stop execution and get a debugger console
	gem 'byebug'
	gem 'rspec'
	gem "rspec-rails"
	gem "factory_girl_rails"
	gem 'capybara'
	gem 'spring-commands-rspec'
	gem 'database_cleaner'

end

group :development do
	# Access an IRB console on exception pages or by using <%= console %> in views
	gem 'web-console', '~> 2.3', '>= 2.3.0'
	gem 'better_errors', '>= 2.8.0'
	gem 'binding_of_caller'
	# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
	#gem 'spring'
end
group :test do
	gem 'webmock', '>= 2.3.2'
	gem 'simplecov'
end
